### ISSUE TITLE
publish a tagged release on luarocks

### ISSUE THREAD

**Issue by teto** [teal-language/teal-language-server#12]
hi,

I would like to package teal-language-server for nixpkgs, and while it's doable as is, I would prefer to package a tagged release (it's also simpler). Otherwise one has to specify the "dev" server to install the software, i.e., luarocks install --server=https://luarocks.org/dev teal-language-server
 https://luarocks.org/modules/3uclidian/teal-language-server

**Comment by svermeulen** [comment]
We've published a tagged release now

**Comment by teto** [comment]
cool thank you !
