### ISSUE TITLE
Switched to tree-sitter for parsing

### ISSUE THREAD

**Issue by FourierTransformer** [teal-language/teal-language-server#24]
I've been playing around with the teal-language-server codebase for the past couple of weeks, and I think it's changed _too much_ and is more of a fork at this point... That wasn't really my intention going into it, but so it goes.

I'm curious if you guys are interested in getting these changes in the main language server repo here, or if you'd rather it just be a fork.

## Main Changes
- I switched to using @euclidianAce's tree-sitter-teal to do parsing of any potentially valid code. The nice thing about using the tree-sitter is that it handles incomplete documents _really well_, and then you can extract tokens in a predictable way.
- It uses the idea of pulling out the tokens as a list and then iterating forward using Teal's `symbols_in_scope` (fully explained here: https://github.com/teal-language/teal-language-server/pull/22#issue-2634269467) to handle completion, hover, go to definition, and signature help. 
  - Tree-sitter solves the `self` problem I encountered before, by just going up the tree, I can easily determine what `self` refers to and use that while looking in the symbol table.
- It handles completion when the user is at a `:`, `.`, or `(`, and also _before_ it.
  - Properly handles filtering functions with `self` by matching the original type on `:` or seeing if the first arg is `self`
  - If you're typing `if foo`, the language server can show all symbols that are in scope while typing `foo`.
- Added LSP completion item kind to the completion results (results in symbols showing up during completion)
- Shows record/enums/polymorphic information on hover
- Also show type info when hovering on `bar` in `foo.bar`
- Switched to using Markdown for the hover and function signature help. It looks a bit nicer, and when teal is more widespread will highlight correctly
- Small perf changes

## Current Big issues
All of these changes don't come without a couple of issues. They should all be resolvable with some time and effort.

### Packaging
- I'm using [ltreesitter](https://github.com/euclidianAce/ltreesitter) for loading the teal tree-sitter grammar, but it requires the tree sitter [lib](https://github.com/tree-sitter/tree-sitter/tree/master/lib) installed on the system as well as the `teal.so` from the grammar to be present.
  - Both of these make it a little hard to just `luarocks install` the langauge server and get things going.
  - I'm not sure if the tree-sitter library is generally included in the bindings and/or how the language gets bundled.
  - I have seen all the tree-sitter grammars used by neovim for languages in [luarocks](https://luarocks.org/search?q=tree-sitter), but I haven't looked into how exactly they are packaging those up.

### With completion
- Method chaining completion currently doesn't work. 
  - While iterating through the symbol table, I could see if it's a function and use the return type for the next item in the list
- Completion after brackets doesn't work.
  - Would need to resolve the type inside the bracket, and then while doing the forward lookup take that into account

## Future plans
- Write some unit tests! Crucial to ensure everything continues to work as changes are made
- Resolve _types_. As folks type `local thing: st`, we know from tree-sitter they are on a type and could help complete types
- Pull in Lua reference manual. Right now all the globals just show type info on hover/function signature help. We could enhance this with argument names and documentation from the [reference manual](https://www.lua.org/manual/5.4/#index)
- Have hover/function signature completion know if it's on a `self` and remove the first argument
- Have function signature highlight which argument is currently being typed
- Pull in comments above functions to display on hover? I _feel_ like a lot of folks comment above a function to explain what something does (or do this via LDoc)

## The Code
Overall I like the switch to tree-sitter, since it eliminates a lot of the "wait 2 chars" and +1/-1 token handling, and gives us _enough_ information during completion requests to nicely handle various scenarios for the user. It also feels easier to maintain while still allowing extensibility in the future.

You can see all the changes here: https://github.com/FourierTransformer/teal-language-server/pull/2 (The code is on this [branch](https://github.com/FourierTransformer/teal-language-server/tree/forked-main)).

I'll probably start tackling some of the issues and future plans, but my time will be significantly more limited in the near future. Again, totally understand if you'd rather not take on such a large change in the codebase.

**Comment by svermeulen** [comment]
Honestly, I don't have a lot of maintainership energy on this project, so would happily hand over the reins of teal-language-server to you and your fork!

All those changes sound great.  I was hoping to integrate tree sitter into the logic too at some point and replace all the hacky per-character logic.

If I have time in the future I'll try switching over to your fork and hopefully help with some of the remaining work

**Comment by svermeulen** [comment]
Ok great.  I invited you as another maintainer

**Comment by FourierTransformer** [comment]
Thanks! I'll probably PR where it's at in in the next day or so and then make some followup stories.
