### ISSUE TITLE
Use some form of non-blocking IO

### ISSUE THREAD

**Issue by euclidianAce** [teal-language/teal-language-server#3]
I think the best candidate for this would be LuaSocket as it:
 - already has typedefs and
 - is cross platform
 - language servers have the option to communicate over sockets, but just use stdio by default
 - And is one of the most popular lua modules so people probably already have it installed

but I'm open to other suggestions like `luv` or `cqueues`

**Comment by cloudfreexiao** [comment]
how to you think about lsocket https://github.com/cloudwu/lsocket

**Comment by svermeulen** [comment]
It does use Luv now
